### ISSUE TITLE
[Help wanted] Add the small streaming zipformer model from icefall #903

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/sherpa-ncnn#107]
https://github.com/k2-fsa/icefall/pull/903 provides a smaller streaming zipformer.

## TODOs
- [ ] Convert it to ncnn format
- [ ] Add documentation for it
- [ ] Add CI test for it

**Comment by marcoyang1998** [comment]
I will do this.

**Comment by marcoyang1998** [comment]
The converted model can be found here https://huggingface.co/marcoyang/sherpa-ncnn-streaming-zipformer-20M-2023-02-17

**Comment by joazoa** [comment]
Is the new Improved Zipformer already supported in ncnn ?

**Comment by csukuangfj** [comment]
> Is the new Improved Zipformer already supported in ncnn ?

No, not yet. We have not converted it to ncnn format yet.

**Comment by joazoa** [comment]
@csukuangfj  do you know if anybody is working on wasm support for onnx or ncnn support for latest zipformer ? (So any way to run the latest zipformer with wasm)

**Comment by csukuangfj** [comment]
> @csukuangfj do you know if anybody is working on wasm support for onnx or ncnn support for latest zipformer ? (So any way to run the latest zipformer with wasm)

I am working on the wasm support of the latest zipformer in sherpa-onnx.

By the way, we have already supported running tts with wasm in sherpa-onnx, which means we have already setup the environment for wasm development and it should not be difficult to support asr with wasm in sherpa-onnx.

**Comment by csukuangfj** [comment]
> @csukuangfj do you know if anybody is working on wasm support for onnx or ncnn support for latest zipformer ? (So any way to run the latest zipformer with wasm)

It has been supported in sherpa-onnx. We support running it both in the browser and in NodeJS via WebAssembly.
@joazoa

**Comment by joazoa** [comment]
Thank you!!
