### ISSUE TITLE
[Help wanted] iOS TODO list

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/sherpa-ncnn#91]
Some TODO lists to improve `sherpa-ncnn` for `iOS`:

- [ ] Improve the user interface
  - [ ] Add a scroll view to view the history recognition result
  - [ ] Increase the size of the `Start` button
  - [ ] Center the hint `ASR with Next-gen Kaldi, Press the Start button` and possibly colorize the texts
- [ ] Add a Swift UI demo

Help from the community is very appreciated.
